module.exports = (sequelize, DataTypes) => {
    const Filme = sequelize.define('Filme', {
        filme_id:{
            type:DataTypes.INTEGER,
            primaryKey:true,
            autoIncrement:true
        },
        titulo:DataTypes.STRING,
        descricao:{
            type:DataTypes.STRING,
            allownNull:true
        },
        ano_de_lancamento:{
            type:DataTypes.DATE,
            allownNull:true
        },
        indioma_id:{
            type:DataTypes.INTEGER,
            allownNull:true
        },
        indioma_original_id:{
            type:DataTypes.INTEGER,
            allownNull:true
        },
        duracao_da_locacao:{
            type:DataTypes.INTEGER
        },
        preco_da_locacao:{
            type:DataTypes.DECIMAL(4,2)
        },
        duracao_do_filme:{
            type:DataTypes.INTEGER, 
            allownNull:true 
        },
        custo_de_substituicao:DataTypes.DECIMAL(5,2),
        classificacao:{
            type:DataTypes.STRING, 
            allownNull:true 
        },
        recursos_especiais:{
            type:DataTypes.STRING, 
            allownNull:true 
        }
        
    },{
        tableName:'filme'
        //estrutura necessária quando não existe o campo timestamp na tabela
        //timestamps:false
    })
}